# Generated by Django 3.0.7 on 2020-06-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativesComparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id', models.IntegerField()),
                ('c_id', models.IntegerField()),
                ('a1', models.IntegerField()),
                ('a2', models.IntegerField()),
                ('a1a2_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AlternativesCriterionsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id', models.IntegerField()),
                ('c_id', models.IntegerField()),
                ('a_id', models.IntegerField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AlternativesNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id', models.IntegerField()),
                ('aname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CriterionsAlternativesAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterions', models.IntegerField()),
                ('alternatives', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CriterionsComparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id', models.IntegerField()),
                ('c1', models.IntegerField()),
                ('c2', models.IntegerField()),
                ('c1c2_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CriterionsNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id', models.IntegerField()),
                ('cname', models.TextField()),
            ],
        ),
    ]
