# Generated by Django 3.0.7 on 2020-06-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativesNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id', models.IntegerField()),
                ('aname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CriterionsAlternativesAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterions', models.IntegerField()),
                ('alternatives', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CriterionsNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id', models.IntegerField()),
                ('cname', models.TextField()),
            ],
        ),
    ]
